version: '3.4'

networks:
  default:
  nginx:
    external:
      name: nginx

volumes:
  ssl:
  nexus-data:

x-logging: &_logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

x-docker-base: &_docker-base
  image: localdev-dind
  build:
    context: ./images/dind
    args:
      - from=docker:stable-dind
  logging:
    <<: *_logging
  privileged: true
  restart: always
  command: [
    "--registry-mirror=https://registry-mirror.local",
    "--swarm-default-advertise-addr=eth0",
  ]
  volumes:
    - ssl:/srv/localdev/ssl:ro

x-docker-slave: &_docker-slave
  <<: *_docker-base
  networks:
    default:
      aliases:
        - docker-slave
  environment:
    - LOCALDEV_VHOST_SUFFIX

x-docker-master: &_docker-master
  <<: *_docker-base
  networks:
    default:
      aliases:
        - docker-master
    nginx:
  environment:
    - LOCALDEV_VHOST_SUFFIX
    - VIRTUAL_HOST=docker-master.${LOCALDEV_VHOST_SUFFIX}

services:
  docker-slave-0:
    <<: *_docker-slave

  docker-slave-1:
    <<: *_docker-slave

  docker-master-0:
    <<: *_docker-master

  nexus:
    image: localdev-nexus3
    build:
      context: ./images/nexus3
      args:
        - from=sonatype/nexus3
    logging:
      <<: *_logging
    networks:
      default:
      nginx:
    volumes:
      - nexus-data:/nexus-data
    restart: always
    environment:
      - LOCALDEV_VHOST_SUFFIX
      - VIRTUAL_HOST=docker-nexus.${LOCALDEV_VHOST_SUFFIX}
      - VIRTUAL_PORT=8081

  nginx:
    image: localdev-nginx
    build:
      context: ./images/nginx
    restart: on-failure
    depends_on:
      - nexus
    networks:
      default:
        aliases:
          - nexus.local
          - registry.local
          - registry-mirror.local
      nginx:
    volumes:
      - ssl:/srv/localdev/ssl:ro
    environment:
      - LOCALDEV_VHOST_SUFFIX
      - CERT_NAME=${LOCALDEV_CERT_NAME}
      - VIRTUAL_HOST=docker-registry-mirror.${LOCALDEV_VHOST_SUFFIX},docker-registry.${LOCALDEV_VHOST_SUFFIX}
      - HTTPS_METHOD=noredirect

  control:
    image: localdev
    build:
      context: ./images/control
    restart: on-failure
    logging:
      <<: *_logging
    depends_on:
      - docker-master-0
      - docker-slave-0
      - docker-slave-1
      - nginx
    volumes:
      - ssl:/srv/localdev/ssl:rw
    environment:
      - DOCKER_HOST=tcp://docker-master
    stop_signal: SIGKILL

