#!/usr/bin/env python

from __future__ import print_function

from collections import defaultdict
import docker
import dockerpty
import json
import os
import re
import shlex
import sys
from time import sleep
import yaml

map_term = os.environ['MAP_TERM']

matched = re.match('^([0-9]*):([0-9]*):(.*)$', map_term)
if matched:
    os.environ['COLUMNS'] = matched.group(1)
    os.environ['LINES'] = matched.group(2)
    os.environ['TERM'] = matched.group(3)

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def escape_compose_name(value):
    return re.sub('[^a-zA-Z0-9]+', '', value)

service_label_re = re.compile('^com\.brainfood\.docker\.localdev\.(target_pwd|target_user)(?:=(.*))?$')
tool_label_re = re.compile('com\.brainfood\.docker\.localdev\.tool\.([^=.]+)(?:\.(target_pwd|target_user))?(?:=(.*))?$')
class Service(object):
    def __init__(self, name, project, config):
        self.name = name
        self.project = project
        self.target_pwd = None
        self.target_user = None
        self.tools = {}

        if 'labels' in config:
            for label_str in config['labels']:
                self.absorbLabel(label_str)

    def absorbLabel(self, label):
        service_label_match = service_label_re.match(label)
        tool_label_match = tool_label_re.match(label)
        if service_label_match:
            self.__dict__[service_label_match.group(1)] = service_label_match.group(2)
        elif tool_label_match:
            tool_name = tool_label_match.group(1)
            tool = self.tools.setdefault(tool_name, ServiceTool(tool_name, self))
            tool.absorbLabel(tool_label_match.group(2), tool_label_match.group(3))

class Tool(object):
    def __init__(self, name):
        self.name = name

class ControllerTool(Tool):
    def __init__(self, name, controller):
        super(ControllerTool, self).__init__(name)
        self.controller = controller

class InvalidTool(Tool):
    def run(self, cmd, args):
        eprint('Could not find tool: %s' % (cmd))
        sys.exit(1)

class ComposeTool(ControllerTool):
    def run(self, cmd, args):
        return self.controller.exec_helper(self.controller.project.container, workdir = self.controller.project.top_dir, command = ['docker-compose', '-f', 'docker-compose.' + cmd + '.yml'] + args)

    def help(self, cmd):
        return ['Call "docker-compose -f docker-compose.${cmd}.yml" ...']

class ExecTool(ControllerTool):
    def run(self, cmd, args):
        if len(args) == 0:
            args.append('bash')
        return self.controller.project.run(workdir = '/', command = args)

    def help(self, cmd):
        return ['Execute a command in the control container for this project.']

class ToolGroup(object):
    def __init__(self, controller, group_name, tools):
        self.group_name = group_name
        found_tools_by_tool = {}
        for tool_name, tool in tools.items():
            found_tool = found_tools_by_tool.setdefault(tool, {'tool': tool, 'names': []})
            found_tool['names'].append(tool_name)

        max_name_length = 0
        for found_tool in found_tools_by_tool.values():
            names = found_tool['names']
            found_tool.pop('names')
            names.sort()
            found_tool['name'] = name = names.pop(0)
            if len(name) > max_name_length:
                max_name_length = len(name)
            found_tool['help'] = help = found_tool['tool'].help(name)
            if len(names):
                help.append('Aliases: ' + ', '.join(names))

        self.max_name_length = max_name_length
        self.found_tools = found_tools_by_tool.values()
        self.found_tools.sort(key=lambda found_tool: found_tool['name'])

    def print(self, indent, max_name_length):
        width = os.environ.get('COLUMNS', 80)
        leader = indent + ' ' * (max_name_length + 1)
        for found_tool in self.found_tools:
            name = found_tool['name']
            help = found_tool['help']
            line_to_print = '%s%s%s ' % (indent, name, ' ' * (max_name_length - len(name)))
            while len(help):
                help_words = help.pop(0).split()
                while len(help_words):
                    while len(help_words) and len(line_to_print) + 1 + len(help_words[0]) < width:
                        line_to_print = line_to_print + ' ' + help_words.pop(0)
                    if len(line_to_print):
                        print(line_to_print)
                    line_to_print = leader

class HelpTool(ControllerTool):
    def run(self, cmd, args):
        print('The following commands are available:')
        print()

        global_tools = ToolGroup(self.controller, 'global', self.controller.tools)
        project_tools = ToolGroup(self.controller, 'project', self.controller.project.tools)

        max_name_length = global_tools.max_name_length
        if project_tools.max_name_length > max_name_length: max_name_length = project_tools.max_name_length

        global_tools.print('    ', max_name_length)
        print('===========')
        project_tools.print('    ', max_name_length)

        return {'ExitCode': 0}

    def help(self, cmd):
        return ['Show what tools are available.']

class ServiceTool(Tool):
    def __init__(self, name, service):
        super(ServiceTool, self).__init__(name)
        self.service = service
        self._target_pwd = None
        self._target_user = None
        self.executable = name

    @property
    def target_pwd(self):
        return self._target_pwd or self.service.target_pwd

    @property
    def target_user(self):
        return self._target_user or self.service.target_user

    def absorbLabel(self, label, value):
        if label == 'target_pwd' or label == 'target_user':
            self.__dict__['_' + label] = value
        elif label is None and value:
            self.executable = value

    def run(self, cmd, args):
        project = self.service.project
        controller = project.controller
        escaped_project_name = escape_compose_name(project.vars['COMPOSE_PROJECT_NAME'])

        labels = {
            'com.docker.compose.project' : escaped_project_name,
            'com.brainfood.docker.localdev.tool.' + cmd: None,
        }
        tool_container = controller.find_container(labels)
        if not tool_container:
            controller.tools['dev'].run('dev', ['up', '-d', self.service.name])
            sleep(1)
            tool_container = controller.find_container(labels)

        if not tool_container:
            eprint('Could not find tool: %s' % (cmd))
            sys.exit(1)

        executable = self.executable
        target_pwd = self.target_pwd
        target_user = self.target_user

        if target_pwd == 'relative':
            relative_dir = os.environ['MAP_PWD'][len(project.top_dir):]
            working_dir = '/srv/app' + relative_dir
        elif target_pwd == 'image':
            working_dir = ''
        else:
            working_dir = '/'

        return controller.exec_helper(container = tool_container, workdir = working_dir, user = target_user, command = [executable] + args)

    def help(self, cmd):
        return ['Run the command in the service.']

class ComposeYml(object):
    def __init__(self, project, data):

        self.services = {}
        self.tools = {}

        compose_structure = yaml.load(data)

        for service_name, service_config in compose_structure['services'].items():
            service = self.services.setdefault(service_name, Service(service_name, project, service_config))

            for tool_name, tool in service.tools.items():
                self.tools[tool_name] = tool

shell_var_re = re.compile('^([^=]+)=(.*)$')
class Project(object):
    def __init__(self, controller, top_dir):
        self.controller = controller
        self.top_dir = top_dir
        self._compose = None
        self._container = None
        self._vars = {}
        self._environment_parsed = False

    @property
    def compose(self):
        self.parse_environment()
        return self._compose

    @property
    def vars(self):
        self.parse_environment()
        return self._vars

    @property
    def tools(self):
        return self.compose.tools

    def get_mapped_file_data(self, filename, environ_key):
        if os.environ.has_key(environ_key):
            return os.environ[environ_key]
        else:
            return self.get_project_file_data(filename)

    def parse_environment(self):
        if self._environment_parsed:
            return

        data = self.get_mapped_file_data('docker-compose.%s.yml' % ('dev'), 'MAP_DEV_YML')
        self._compose = ComposeYml(self, data)

        data = self.get_mapped_file_data('.env', 'MAP_ENV')
        for line in shlex.split(data, True):
            shell_var_match = shell_var_re.match(line)
            if shell_var_match:
                self._vars[shell_var_match.group(1)] = shell_var_match.group(2)

        self._environment_parsed = True

    def get_project_file_data(self, relative_path):
        f = open('/srv/localdev/global_root/' + self.top_dir + '/' + relative_path, 'r')
        data = f.read()
        f.close()
        return data

    @property
    def container(self):
        if self._container: return self._container

        labels = {
            'com.brainfood.docker.localdev.top_dir': self.top_dir,
        }

        container = self.controller.find_container(labels)
        if container:
            container_image_hash = container.attrs['Image']

            if container.attrs['Image'] != 'localdev':
                container.remove(force = True)
            elif not 'localdev_default' in container.attrs['NetworkSettings']['Networks']:
                container.remove(force = True)
            else:
                self._container = container
                return container

        container_config = {
            'labels': labels,
            'network': 'localdev_default',
            'volumes': {
                self.top_dir: {'bind': self.top_dir, 'mode': 'rw'},
                '/var/run/docker.sock': {'bind': '/var/run/docker.sock', 'mode': 'rw'},
            },
        }

        container = self.controller.docker.containers.create('localdev', detach = True, **container_config)
        container.start()
        self._container = container
        return container

    def run(self, command = None, workdir = os.environ['MAP_PWD']):
        command = ['/srv/localdev/scripts/exec-helper'] + command
        environment = {
            'MAP_USER': os.environ['MAP_USER'],
            'MAP_UMASK': os.environ['MAP_UMASK'],
        }

        return self.controller.exec_helper(self.container, environment = environment, workdir = workdir, command = command)

class Controller():
    def __init__(self):
        self._docker = None

        self.project = Project(self, os.environ['MAP_TOP_DIR'])

        self.tools = {}
        self.tools['dev'] = self.tools['prod'] = ComposeTool('compose', self)
        self.tools['exec'] = ExecTool('exec', self)
        self.tools['help'] = HelpTool('help', self)

    @property
    def docker(self):
        if not self._docker:
            self._docker = docker.from_env()
        return self._docker

    def find_container(self, labels):
        label_filters = []
        for label, value in labels.items():
            if value:
                label_filters.append(label + '=' + value)
            else:
                label_filters.append(label)

        found = self.docker.containers.list(all = True, filters = {'label': label_filters}, sparse = True)
        while len(found) > 1:
            found[0].remove(force = True)
            found.pop(0)

        if len(found) == 1:
            return found[0]

    def exec_helper(self, container, environment = {}, workdir = '/', user = None, command = []):
        isatty = sys.stdout.isatty()
        api = self.docker.api
        environment = environment.copy()
        environment.update({
            'COLUMNS': os.environ.get('COLUMNS'),
            'LINES': os.environ.get('LINES'),
            'TERM': os.environ.get('TERM'),
        })
        result = api.exec_create(
            container.id,
            command,
            stdin = True,
            tty = isatty,
            user = user,
            workdir = workdir,
            environment = environment,
        )
        dockerpty.start_exec(api, result['Id'], isatty)
        return api.exec_inspect(result['Id'])

    def run_tool(self, cmd, args):
        if cmd in self.tools:
            tool = self.tools[cmd]
        else:
            tool = self.project.tools[cmd]
        return tool.run(cmd, args)

    def cmd(self, command):
        cmd = command.pop(0)
        return self.run_tool(cmd, command)

controller = Controller()

command = sys.argv[1:]
sys.exit(controller.cmd(command)['ExitCode'])
