FROM nginx as nginx

COPY nginx-files /tmp/files
ARG NGINX_UPGRADE
RUN ["/tmp/files/configure.sh"]

ENTRYPOINT ["/srv/localdev/scripts/entrypoint"]
HEALTHCHECK --interval=15s CMD ["/srv/localdev/scripts/healthcheck"]
